steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'backend/Dockerfile.prod'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:latest'
      - './backend'
    dir: '.'

  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'frontend/Dockerfile.prod'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:latest'
      - './frontend'
    dir: '.'

  # Push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:latest'

  # Push the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:latest'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kick-predictor-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kick-predictor-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'

# The images to store
images:
  - 'gcr.io/$PROJECT_ID/kick-predictor-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/kick-predictor-backend:latest'
  - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/kick-predictor-frontend:latest'

# Configure Cloud Build to use a machine with more resources
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# Timeout setting for the build pipeline
timeout: '1800s'