steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'backend/Dockerfile.prod'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:cb-test'
      - './backend'
    dir: '.'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:cb-test'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kick-predictor-backend-cb'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kick-predictor-backend:cb-test'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '5'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'

# Configure Cloud Build to use a machine with more resources
options:
  machineType: 'E2_HIGHCPU_8'

# Set timeout for the entire build
timeout: '1200s'