runtime: python311
instance_class: F2

env_variables:
  # Hier Umgebungsvariablen einfügen
  ENVIRONMENT: "production"

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65