name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west3

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      
      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t gcr.io/$PROJECT_ID/kick-predictor-backend:${{ github.sha }} .
          docker tag gcr.io/$PROJECT_ID/kick-predictor-backend:${{ github.sha }} gcr.io/$PROJECT_ID/kick-predictor-backend:latest
          docker push gcr.io/$PROJECT_ID/kick-predictor-backend:${{ github.sha }}
          docker push gcr.io/$PROJECT_ID/kick-predictor-backend:latest
      
      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: kick-predictor-backend
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/kick-predictor-backend:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            ENVIRONMENT=production
            ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          
      - name: Build and Push Frontend with Backend URL
        run: |
          cd frontend
          # Setze die Backend-URL für den Frontend-Build
          echo "VITE_API_URL=${{ steps.deploy-backend.outputs.url }}" > .env.production.local
          
          docker build -t gcr.io/$PROJECT_ID/kick-predictor-frontend:${{ github.sha }} \
            --build-arg VITE_API_URL=${{ steps.deploy-backend.outputs.url }} .
          docker tag gcr.io/$PROJECT_ID/kick-predictor-frontend:${{ github.sha }} gcr.io/$PROJECT_ID/kick-predictor-frontend:latest
          docker push gcr.io/$PROJECT_ID/kick-predictor-frontend:${{ github.sha }}
          docker push gcr.io/$PROJECT_ID/kick-predictor-frontend:latest
      
      - name: Deploy Frontend to Cloud Run
        id: deploy-frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: kick-predictor-frontend
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/kick-predictor-frontend:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            NODE_ENV=production
            BACKEND_URL=${{ steps.deploy-backend.outputs.url }}
            
      - name: Show deployed URLs
        run: |
          echo "Backend deployed to: ${{ steps.deploy-backend.outputs.url }}"
          echo "Frontend deployed to: ${{ steps.deploy-frontend.outputs.url }}"